### ISSUE TITLE
GPy.tests() fails on Windows 32bit python 2.7

### ISSUE THREAD

**Issue by CatherallConsulting** [SheffieldML/GPy#234]
Using python 2.7, on Windows 32bit with SciPy 0.16 (32bit python 2.7) I get the following in ipython after installing the latest GPy and running the tests:

======================================================================
ERROR: test_nonsym (GPy.testing.kernel_tests.Coregionalize_cython_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\testing\kernel_tests.py", line 415, in test_nonsym
    self.k.update_gradients_full(dL_dK, self.X, self.X2)
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\kern\_src\kernel_slice_operations.py", line 95, in wrap
    ret = f(self, dL_dK, s.X, s.X2)
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\kern\_src\coregionalize.py", line 96, in update_gradients_full
    dL_dK_small = self._gradient_reduce_cython(dL_dK, index, index2)
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\kern\_src\coregionalize.py", line 119, in _gradient_reduce_cython
    return coregionalize_cython.gradient_reduce(self.B.shape[0], dL_dK, index, index2)
  File "GPy/kern/_src/coregionalize_cython.pyx", line 27, in GPy.kern._src.coregionalize_cython.gradient_reduce (GPy/kern/_src/coregionalize_cython.c:2075)
    def gradient_reduce(int D, np.ndarray[double, ndim=2] dL_dK, np.ndarray[np.int64_t, ndim=1] index, np.ndarray[np.int64_t, ndim=1] index2):
ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'
-------------------- >> begin captured logging << --------------------
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_sym (GPy.testing.kernel_tests.Coregionalize_cython_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\testing\kernel_tests.py", line 396, in test_sym
    self.k.update_gradients_full(dL_dK, self.X)
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\kern\_src\kernel_slice_operations.py", line 95, in wrap
    ret = f(self, dL_dK, s.X, s.X2)
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\kern\_src\coregionalize.py", line 96, in update_gradients_full
    dL_dK_small = self._gradient_reduce_cython(dL_dK, index, index2)
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\kern\_src\coregionalize.py", line 119, in _gradient_reduce_cython
    return coregionalize_cython.gradient_reduce(self.B.shape[0], dL_dK, index, index2)
  File "GPy/kern/_src/coregionalize_cython.pyx", line 27, in GPy.kern._src.coregionalize_cython.gradient_reduce (GPy/kern/_src/coregionalize_cython.c:2075)
    def gradient_reduce(int D, np.ndarray[double, ndim=2] dL_dK, np.ndarray[np.int64_t, ndim=1] index, np.ndarray[np.int64_t, ndim=1] index2):
ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'
-------------------- >> begin captured logging << --------------------
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_Logexp (GPy.testing.rv_transformation_tests.RVTransformationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\testing\rv_transformation_tests.py", line 65, in test_Logexp
    self._test_trans(GPy.constraints.Exponent())
  File "C:\Anaconda\lib\site-packages\gpy-0.8.0-py2.7-win32.egg\GPy\testing\rv_transformation_tests.py", line 61, in _test_trans
    self.assertTrue(m.checkgrad(verbose=True))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 337 tests in 26.768s

FAILED (SKIP=2, errors=2, failures=1)

In [4]:

**Comment by Dapid** [comment]
How did you install Python? Which compiler was used? You can see it when you run Python, in my case:

    Python 2.7.10 (default, Jul  5 2015, 14:15:43) 
    [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 

My guess is that this is one of these cases where "long" and the such differ with platform. My solution would be to always use Numpy's definitions, and fused types, so we can run it on float32 and float64.

**Comment by CatherallConsulting** [comment]
I installed it with Anaconda, here's the cmd output when I run python

![image](https://cloud.githubusercontent.com/assets/11683408/9762247/970217fa-5702-11e5-8157-1e028b3e079a.png)

**Comment by lawrennd** [comment]
Out of curiosity is there a reason you're using Windows 32 bit? I seem to
remember we've had problems with it before, and I think it is very unusual
nowadays to be using it. @mikecroucher have we tested on the Windows 32 bit
platform? Is there a reason people will want to be using 32 bit?

**Comment by mikecroucher** [comment]
Yes, Windows 32bit is still used a lot.

At Sheffield, for example, the managed desktop is currently 32bit Windows by default. They are migrating to 64bit but there will be 32bit machines all over the place. (I know!...I was astonished too!)

**Comment by mikecroucher** [comment]
I think I have a fix. Currently testing.

**Comment by mikecroucher** [comment]
Fixed in the 0.8.8 release which is now available via pip.

    pip install GPy

I've uploaded and tested a binary for 32 bit Windows 7, Python 2.7 so it should work out of the box. I haven't built a binary for python 3.4 on 32 bit windows yet though.

**Comment by nfusi** [comment]
I still get a failure in a gradient:

```
  FAIL: test_Logexp (GPy.testing.rv_transformation_tests.RVTransformationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\fusi\OneDrive\Work\Projects\GPy\GPy\testing\rv_transformation_tests.py", line 65, in test_Logexp
    self._test_trans(GPy.constraints.Exponent())
  File "C:\Users\fusi\OneDrive\Work\Projects\GPy\GPy\testing\rv_transformation_tests.py", line 61, in _test_trans
    self.assertTrue(m.checkgrad(verbose=True))
AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |   5.035323    |   5.035323    |     1e-04
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |   -9.238314   |   -9.238314   |     2e-05
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |   5.399716    |   5.399716    |     4e-04
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |  -10.041274   |  -10.041274   |     2e-05
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |   -2.261675   |   -2.261675   |     8e-06
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |   -3.995744   |   -3.995744   |     2e-05
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |   -4.196382   |   -4.196382   |     2e-05
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |   2.089746    |   2.089746    |     7e-06
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |  -11.902225   |  -11.902225   |     1e-05
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   1.000000    |   0.000000    |   -0.057354   |   -0.057354   |     2e-07
           Name           |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio
----------------------------------------------------------------------------------------------------------
 test_model.theta[[0]]    |   0.386835    |   2.653941    |   -4.328267   |   -1.674326   |     2e-06

--------------------- >> end captured stdout << ----------------------
    'False is not true' = self._formatMessage('False is not true', "%s is not true" % safe_repr(False))
>>  raise self.failureException('False is not true')

-------------------- >> begin captured logging << --------------------
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
parameters changed meta: DEBUG: finished init
parameters changed meta: DEBUG: connecting parameters
parameters changed meta: DEBUG: calling parameters changed
--------------------- >> end captured logging << ---------------------
```

Do you think this is Windows specific? I see that the build is passing on Travis.

**Comment by mikecroucher** [comment]
Yes, it is Windows-specific. We are finding minor, platform-specific numerical issues in various places.

For example - https://github.com/SheffieldML/GPy/issues/228

**Comment by mzwiessele** [comment]
#249

**Comment by mzwiessele** [comment]
#226

**Comment by mzwiessele** [comment]
I am skipping the Logexp test for now, will have a look for the next patch. ff40c2bc5762010961a2d7efcc4c740052b6a35b

**Comment by CatherallConsulting** [comment]
I've installed the latest version of GPy (using pip) and am still getting failed tests on 32bit windows, mostly "expected 'int64_t' but got 'long'" but also the failed assert in test_Logexp.

**Comment by mzwiessele** [comment]
Dont worry too much about the LogExp error, there seems to be a bug somewhere. We werent able to pinpoint it as of yet though... 

As of win32, I cannot help, as we have not got access to a win32 system. maybe someone else have resolved this on their machine?

**Comment by mikecroucher** [comment]
I have a 32bit Windows VM. The failures ``"expected 'int64_t' but got 'long'"`` no longer appear on that system which is a completely clean install of both Python and GPy 0.8.8 via pip.

    >>> GPy.__version__
    '0.8.8'

This test always fails, however:

    FAIL: test_Logexp (GPy.testing.rv_transformation_tests.RVTransformationTestCase)

This test occasionally fails:

    FAIL: test_inferenceX_BGPLVM (GPy.testing.inference_tests.InferenceXTestCase)

**Comment by mzwiessele** [comment]
We know about the logexp error

@zenwhendai can you have a look at a seed for the inference for X test?

**Comment by mzwiessele** [comment]
Any news, can I close?

**Comment by mzwiessele** [comment]
Fixed by #262
