### ISSUE TITLE
Active dimensions incorrect for products of kernels

### ISSUE THREAD

**Issue by jluttine** [SheffieldML/GPy#325]
Hi! I'm not sure whether this is a bug or not, but at least I find it confusing. When I multiply two kernels, the active dimensions doesn't seem to be the union of the active dimensions of the two kernels as I'd expect:

``` python
>>> kern1 = GPy.kern.RBF(input_dim=1, active_dims=[2])
>>> kern2 = GPy.kern.RBF(input_dim=1, active_dims=[4])
>>> kern = kern1 * kern2
>>> print(kern1.active_dims)
[2]
>>> print(kern2.active_dims)
[4]
>>> print(kern.active_dims)
[0 1 2 3 4]
```

That is, I would have expected the last line to print out `[2 4]`. Is this a bug, have I misunderstood something or am I doing something wrong?

**Comment by mzwiessele** [comment]
Good point Jaakko, this has been fixed on the devel branch of GPy, which we are working hard on to bring forward as a new release.

**Comment by jluttine** [comment]
I'm using the devel branch (latest commit af76126ef19b81cc6586ab6db4b32a9e7d3844f2) but I still see this issue. Am I missing something?

**Comment by mzwiessele** [comment]
I'm on it, almost fixed : )

**Comment by jluttine** [comment]
Nice, thanks a lot! :)
